from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import (QMainWindow, QPushButton, QWidget, QGridLayout,
                             QStyle, QGroupBox, QLineEdit, QCheckBox,
                             QVBoxLayout, QHBoxLayout, QLabel, QColorDialog,
                             QComboBox)
from pandasvis.utils.classes import CollapsibleBox
from pandasvis.utils.functions import AutoDictionary


class LayoutDialog(QMainWindow):
    def __init__(self, parent):
        super().__init__(parent)
        self.setWindowTitle("Layout for " + parent.name)
        self.setWindowFlags(
            QtCore.Qt.Window |
            QtCore.Qt.CustomizeWindowHint |
            QtCore.Qt.WindowTitleHint |
            QtCore.Qt.WindowCloseButtonHint
        )
        self.resize(600, 600)
        self.parent = parent

        self.onlyInt = QtGui.QIntValidator()
        all_fonts = ["Arial", "Balto", "Courier New", "Droid Sans",
                     "Droid Serif", "Droid Sans Mono", "Gravitas One",
                     "Old Standard TT", "Open Sans", "Overpass",
                     "PT Sans Narrow", "Raleway", "Times New Roman"]

        self.bt_uplayout = QPushButton('Update layout')
        self.bt_uplayout.setIcon(self.style().standardIcon(QStyle.SP_BrowserReload))
        self.bt_uplayout.clicked.connect(self.layout_update)

        self.bt_close = QPushButton('Close')
        self.bt_close.setIcon(self.style().standardIcon(QStyle.SP_DialogCloseButton))
        #self.bt_close.clicked.connect(self.choose_font)

        self.hbox = QHBoxLayout()
        self.hbox.addWidget(self.bt_uplayout)
        self.hbox.addWidget(self.bt_close)
        self.hbox.addWidget(QWidget())
        self.hbox.addStretch()

        # Overal Layout parameters
        self.lbl_layhover = QLabel('hovermode:')
        self.combo_layhover = QComboBox()
        self.combo_layhover.addItem('closest')
        self.combo_layhover.addItem('x')
        self.combo_layhover.addItem('y')
        self.combo_layhover.addItem('False')
        self.chk_layautosize = QCheckBox('autosize')
        self.chk_layautosize.setChecked(True)
        self.lbl_laywidth = QLabel('width:')
        self.lin_laywidth = QLineEdit('700')
        self.lin_laywidth.setValidator(self.onlyInt)
        self.lbl_layheight = QLabel('height:')
        self.lin_layheight = QLineEdit('450')
        self.lin_layheight.setValidator(self.onlyInt)
        self.lbl_layfont = QLabel('font:')
        self.combo_layfont = QComboBox()
        for ft in all_fonts:
            self.combo_layfont.addItem(ft)
        self.lin_layfont = QLineEdit('10')
        self.lin_layfont.setValidator(self.onlyInt)
        self.lbl_layfontc = QLabel('font color (r,g,b,a):')
        self.btn_layfontc = QPushButton('Pick')
        self.btn_layfontc.clicked.connect(lambda: self.choose_color(target='layout_font'))
        self.lin_layfontr = QLineEdit('0')
        self.lin_layfontr.setValidator(self.onlyInt)
        self.lin_layfontg = QLineEdit('0')
        self.lin_layfontg.setValidator(self.onlyInt)
        self.lin_layfontb = QLineEdit('0')
        self.lin_layfontb.setValidator(self.onlyInt)
        self.lin_layfonta = QLineEdit('255')
        self.lin_layfonta.setValidator(self.onlyInt)
        self.lbl_laypaperc = QLabel('paper color (r,g,b,a):')
        self.btn_laypaperc = QPushButton('Pick')
        self.btn_laypaperc.clicked.connect(lambda: self.choose_color(target='layout_paper'))
        self.lin_laypaperr = QLineEdit('255')
        self.lin_laypaperr.setValidator(self.onlyInt)
        self.lin_laypaperg = QLineEdit('255')
        self.lin_laypaperg.setValidator(self.onlyInt)
        self.lin_laypaperb = QLineEdit('255')
        self.lin_laypaperb.setValidator(self.onlyInt)
        self.lin_laypapera = QLineEdit('255')
        self.lin_laypapera.setValidator(self.onlyInt)
        self.lbl_layplotc = QLabel('plot_bg color (r,g,b,a):')
        self.btn_layplotc = QPushButton('Pick')
        self.btn_layplotc.clicked.connect(lambda: self.choose_color(target='layout_plot'))
        self.lin_layplotr = QLineEdit('255')
        self.lin_layplotr.setValidator(self.onlyInt)
        self.lin_layplotg = QLineEdit('255')
        self.lin_layplotg.setValidator(self.onlyInt)
        self.lin_layplotb = QLineEdit('255')
        self.lin_layplotb.setValidator(self.onlyInt)
        self.lin_layplota = QLineEdit('255')
        self.lin_layplota.setValidator(self.onlyInt)
        self.chk_legend = QCheckBox('show legend')
        self.chk_legend.setChecked(True)

        self.general_grid = QGridLayout()
        self.general_grid.setColumnStretch(7, 1)
        self.general_grid.addWidget(self.lbl_layhover, 0, 0, 1, 1)
        self.general_grid.addWidget(self.combo_layhover, 0, 1, 1, 1)
        self.general_grid.addWidget(self.chk_layautosize, 1, 0, 1, 1)
        self.general_grid.addWidget(self.lbl_laywidth, 2, 0, 1, 1)
        self.general_grid.addWidget(self.lin_laywidth, 2, 1, 1, 1)
        self.general_grid.addWidget(self.lbl_layheight, 3, 0, 1, 1)
        self.general_grid.addWidget(self.lin_layheight, 3, 1, 1, 1)
        self.general_grid.addWidget(self.lbl_layfont, 4, 0, 1, 1)
        self.general_grid.addWidget(self.lin_layfont, 4, 1, 1, 1)
        self.general_grid.addWidget(self.combo_layfont, 4, 2, 1, 2)
        self.general_grid.addWidget(self.lbl_layfontc, 5, 0, 1, 1)
        self.general_grid.addWidget(self.lin_layfontr, 5, 1, 1, 1)
        self.general_grid.addWidget(self.lin_layfontg, 5, 2, 1, 1)
        self.general_grid.addWidget(self.lin_layfontb, 5, 3, 1, 1)
        self.general_grid.addWidget(self.lin_layfonta, 5, 4, 1, 1)
        self.general_grid.addWidget(self.btn_layfontc, 5, 5, 1, 1)
        self.general_grid.addWidget(self.lbl_laypaperc, 6, 0, 1, 1)
        self.general_grid.addWidget(self.lin_laypaperr, 6, 1, 1, 1)
        self.general_grid.addWidget(self.lin_laypaperg, 6, 2, 1, 1)
        self.general_grid.addWidget(self.lin_laypaperb, 6, 3, 1, 1)
        self.general_grid.addWidget(self.lin_laypapera, 6, 4, 1, 1)
        self.general_grid.addWidget(self.btn_laypaperc, 6, 5, 1, 1)
        self.general_grid.addWidget(self.lbl_layplotc, 7, 0, 1, 1)
        self.general_grid.addWidget(self.lin_layplotr, 7, 1, 1, 1)
        self.general_grid.addWidget(self.lin_layplotg, 7, 2, 1, 1)
        self.general_grid.addWidget(self.lin_layplotb, 7, 3, 1, 1)
        self.general_grid.addWidget(self.lin_layplota, 7, 4, 1, 1)
        self.general_grid.addWidget(self.btn_layplotc, 7, 5, 1, 1)
        self.general_grid.addWidget(self.chk_legend, 8, 0, 1, 1)
        self.general_grid.addWidget(QWidget(), 9, 0, 1, 7)

        self.general_group = CollapsibleBox(title='General', parent=self)
        self.general_group.setContentLayout(self.general_grid)


        # Title parameters
        self.lbl_titletext = QLabel('text:')
        self.lin_titletext = QLineEdit('')
        self.lbl_titlefont = QLabel('font:')
        self.combo_titlefont = QComboBox()
        for ft in all_fonts:
            self.combo_titlefont.addItem(ft)
        self.lin_titlefont = QLineEdit('18')
        self.lin_titlefont.setValidator(self.onlyInt)
        self.lbl_titlec = QLabel('color (r,g,b,a):')
        self.btn_titlec = QPushButton('Pick')
        self.btn_titlec.clicked.connect(lambda: self.choose_color(target='title'))
        self.lin_titler = QLineEdit('0')
        self.lin_titler.setValidator(self.onlyInt)
        self.lin_titleg = QLineEdit('0')
        self.lin_titleg.setValidator(self.onlyInt)
        self.lin_titleb = QLineEdit('0')
        self.lin_titleb.setValidator(self.onlyInt)
        self.lin_titlea = QLineEdit('255')
        self.lin_titlea.setValidator(self.onlyInt)

        self.title_grid = QGridLayout()
        self.title_grid.setColumnStretch(7, 1)
        self.title_grid.addWidget(self.lbl_titletext, 0, 0, 1, 1)
        self.title_grid.addWidget(self.lin_titletext, 0, 1, 1, 3)
        self.title_grid.addWidget(self.lbl_titlefont, 1, 0, 1, 1)
        self.title_grid.addWidget(self.lin_titlefont, 1, 1, 1, 1)
        self.title_grid.addWidget(self.combo_titlefont, 1, 2, 1, 2)
        self.title_grid.addWidget(self.lbl_titlec, 2, 0, 1, 1)
        self.title_grid.addWidget(self.lin_titler, 2, 1, 1, 1)
        self.title_grid.addWidget(self.lin_titleg, 2, 2, 1, 1)
        self.title_grid.addWidget(self.lin_titleb, 2, 3, 1, 1)
        self.title_grid.addWidget(self.lin_titlea, 2, 4, 1, 1)
        self.title_grid.addWidget(self.btn_titlec, 2, 5, 1, 1)

        self.title_group = CollapsibleBox(title='Title', parent=self)
        self.title_group.setContentLayout(self.title_grid)

        # X Axis parameters
        self.chk_xvisible = QCheckBox('visible')
        self.chk_xvisible.setChecked(True)
        self.lbl_xc = QLabel('color (r,g,b,a):')
        self.btn_xc = QPushButton('Pick')
        self.btn_xc.clicked.connect(lambda: self.choose_color(target='xaxis'))
        self.lin_xr = QLineEdit('255')
        self.lin_xr.setValidator(self.onlyInt)
        self.lin_xg = QLineEdit('255')
        self.lin_xg.setValidator(self.onlyInt)
        self.lin_xb = QLineEdit('255')
        self.lin_xb.setValidator(self.onlyInt)
        self.lin_xa = QLineEdit('255')
        self.lin_xa.setValidator(self.onlyInt)
        self.lbl_xtitletext = QLabel('text:')
        self.lin_xtitletext = QLineEdit('')
        self.lbl_xtitlefont = QLabel('font:')
        self.combo_xtitlefont = QComboBox()
        for ft in all_fonts:
            self.combo_xtitlefont.addItem(ft)
        self.lin_xtitlefont = QLineEdit('10')
        self.lin_xtitlefont.setValidator(self.onlyInt)
        self.lbl_xtitlec = QLabel('font color (r,g,b,a):')
        self.btn_xtitlec = QPushButton('Pick')
        self.btn_xtitlec.clicked.connect(lambda: self.choose_color(target='xaxis_title'))
        self.lin_xtitler = QLineEdit('27')
        self.lin_xtitler.setValidator(self.onlyInt)
        self.lin_xtitleg = QLineEdit('27')
        self.lin_xtitleg.setValidator(self.onlyInt)
        self.lin_xtitleb = QLineEdit('27')
        self.lin_xtitleb.setValidator(self.onlyInt)
        self.lin_xtitlea = QLineEdit('255')
        self.lin_xtitlea.setValidator(self.onlyInt)
        self.lbl_xtype = QLabel('type:')
        self.combo_xtype = QComboBox()
        self.combo_xtype.addItem("-")
        self.combo_xtype.addItem("linear")
        self.combo_xtype.addItem("log")
        self.combo_xtype.addItem("date")
        self.combo_xtype.addItem("category")
        self.combo_xtype.addItem("multicategory")
        self.chk_xautorange = QCheckBox('autorange')
        self.chk_xautorange.setChecked(True)
        self.lbl_xnticks = QLabel('nticks:')
        self.lin_xnticks = QLineEdit('4')
        self.lin_xnticks.setValidator(self.onlyInt)
        self.lbl_xticks = QLabel('ticks:')
        self.combo_xticks = QComboBox()
        self.combo_xticks.addItem("inside")
        self.combo_xticks.addItem("outside")
        self.combo_xticks.addItem("")
        self.lbl_xticklen = QLabel('tick length:')
        self.lin_xticklen = QLineEdit('5')
        self.lin_xticklen.setValidator(self.onlyInt)
        self.lbl_xtickwid = QLabel('tick width:')
        self.lin_xtickwid = QLineEdit('1')
        self.lin_xtickwid.setValidator(self.onlyInt)
        self.lbl_xtickc = QLabel('tick color (r,g,b,a):')
        self.btn_xtickc = QPushButton('Pick')
        self.btn_xtickc.clicked.connect(lambda: self.choose_color(target='xaxis_tick'))
        self.lin_xtickr = QLineEdit('27')
        self.lin_xtickr.setValidator(self.onlyInt)
        self.lin_xtickg = QLineEdit('27')
        self.lin_xtickg.setValidator(self.onlyInt)
        self.lin_xtickb = QLineEdit('27')
        self.lin_xtickb.setValidator(self.onlyInt)
        self.lin_xticka = QLineEdit('255')
        self.lin_xticka.setValidator(self.onlyInt)
        self.chk_xshowticklabels = QCheckBox('show tick labels')
        self.chk_xshowticklabels.setChecked(True)
        self.lbl_xtickangle = QLabel('tick angle:')
        self.chk_xtickangle = QCheckBox('auto')
        self.chk_xtickangle.setChecked(True)
        self.lin_xtickangle = QLineEdit('0')
        self.lin_xtickangle.setValidator(self.onlyInt)
        self.lbl_xtickprefix = QLabel('tick prefix:')
        self.lin_xtickprefix = QLineEdit('')
        self.combo_xshowtickprefix = QComboBox()
        self.combo_xshowtickprefix.addItem("all")
        self.combo_xshowtickprefix.addItem("first")
        self.combo_xshowtickprefix.addItem("last")
        self.combo_xshowtickprefix.addItem("none")
        self.lbl_xticksufix = QLabel('tick sufix:')
        self.lin_xticksufix = QLineEdit('')
        self.combo_xshowticksufix = QComboBox()
        self.combo_xshowticksufix.addItem("all")
        self.combo_xshowticksufix.addItem("first")
        self.combo_xshowticksufix.addItem("last")
        self.combo_xshowticksufix.addItem("none")
        self.lbl_xexponent = QLabel('exponent:')
        self.combo_xexponent = QComboBox()
        self.combo_xexponent.addItem("B")
        self.combo_xexponent.addItem("e")
        self.combo_xexponent.addItem("E")
        self.combo_xexponent.addItem("power")
        self.combo_xexponent.addItem("SI")
        self.combo_xexponent.addItem("none")
        self.combo_xshowexponent = QComboBox()
        self.combo_xshowexponent.addItem("all")
        self.combo_xshowexponent.addItem("first")
        self.combo_xshowexponent.addItem("last")
        self.combo_xshowexponent.addItem("none")
        self.lbl_xtickformat = QLabel('tick format:')
        self.lin_xtickformat = QLineEdit('')
        self.chk_xshowline = QCheckBox('show line')
        self.chk_xshowline.setChecked(False)


        self.xaxis_grid = QGridLayout()
        self.xaxis_grid.setColumnStretch(7, 1)
        self.xaxis_grid.addWidget(self.chk_xvisible, 0, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xc, 1, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xr, 1, 1, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xg, 1, 2, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xb, 1, 3, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xa, 1, 4, 1, 1)
        self.xaxis_grid.addWidget(self.btn_xc, 1, 5, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xtitletext, 2, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtitletext, 2, 1, 1, 3)
        self.xaxis_grid.addWidget(self.lbl_xtitlefont, 3, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtitlefont, 3, 1, 1, 1)
        self.xaxis_grid.addWidget(self.combo_xtitlefont, 3, 2, 1, 2)
        self.xaxis_grid.addWidget(self.lbl_xtitlec, 4, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtitler, 4, 1, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtitleg, 4, 2, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtitleb, 4, 3, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtitlea, 4, 4, 1, 1)
        self.xaxis_grid.addWidget(self.btn_xtitlec, 4, 5, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xtype, 5, 0, 1, 1)
        self.xaxis_grid.addWidget(self.combo_xtype, 5, 1, 1, 2)
        self.xaxis_grid.addWidget(self.chk_xautorange, 6, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xnticks, 7, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xnticks, 7, 1, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xticks, 8, 0, 1, 1)
        self.xaxis_grid.addWidget(self.combo_xticks, 8, 1, 1, 2)
        self.xaxis_grid.addWidget(self.lbl_xticklen, 9, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xticklen, 9, 1, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xtickwid, 10, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtickwid, 10, 1, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xtickc, 11, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtickr, 11, 1, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtickg, 11, 2, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtickb, 11, 3, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xticka, 11, 4, 1, 1)
        self.xaxis_grid.addWidget(self.btn_xtickc, 11, 5, 1, 1)
        self.xaxis_grid.addWidget(self.chk_xshowticklabels, 12, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xtickangle, 13, 0, 1, 1)
        self.xaxis_grid.addWidget(self.chk_xtickangle, 13, 1, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtickangle, 13, 2, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xtickprefix, 14, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtickprefix, 14, 1, 1, 1)
        self.xaxis_grid.addWidget(self.combo_xshowtickprefix, 14, 2, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xticksufix, 15, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xticksufix, 15, 1, 1, 1)
        self.xaxis_grid.addWidget(self.combo_xshowticksufix, 15, 2, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xexponent, 16, 0, 1, 1)
        self.xaxis_grid.addWidget(self.combo_xexponent, 16, 1, 1, 1)
        self.xaxis_grid.addWidget(self.combo_xshowexponent, 16, 2, 1, 1)
        self.xaxis_grid.addWidget(self.lbl_xtickformat, 17, 0, 1, 1)
        self.xaxis_grid.addWidget(self.lin_xtickformat, 17, 1, 1, 1)

        self.xaxis_grid.addWidget(self.chk_xshowline, 18, 0, 1, 1)


        self.xaxis_group = CollapsibleBox(title='X Axis', parent=self)
        self.xaxis_group.setContentLayout(self.xaxis_grid)


        # Y Axis parameters
        self.lbl_ytitle = QLabel('y title')
        self.lin_ytitle = QLineEdit('')

        self.yaxis_grid = QGridLayout()
        self.yaxis_grid.setColumnStretch(7, 1)
        self.yaxis_grid.addWidget(self.lbl_ytitle, 0, 0, 1, 1)
        self.yaxis_grid.addWidget(self.lin_ytitle, 0, 1, 1, 2)

        self.yaxis_group = CollapsibleBox(title='Y Axis', parent=self)
        self.yaxis_group.setContentLayout(self.yaxis_grid)

        # Main window layout
        self.vbox = QVBoxLayout()
        self.vbox.addWidget(self.general_group)
        self.vbox.addWidget(self.title_group)
        self.vbox.addWidget(self.xaxis_group)
        self.vbox.addWidget(self.yaxis_group)
        self.vbox.addStretch()
        self.vbox.addLayout(self.hbox)

        centralWidget = QWidget()
        centralWidget.setLayout(self.vbox)
        self.setCentralWidget(centralWidget)
        self.show()

        self.init_attributes()

        #self.general_group.toggle_button.click()
        #self.title_group.toggle_button.click()
        self.xaxis_group.toggle_button.click()
        #self.yaxis_group.toggle_button.click()

    def choose_color(self, target):
        color = QColorDialog.getColor()
        if color.isValid():
            if target=='title':
                self.lin_titler.setText(str(color.red()))
                self.lin_titleg.setText(str(color.green()))
                self.lin_titleb.setText(str(color.blue()))
            elif target=='layout_font':
                self.lin_layfontr.setText(str(color.red()))
                self.lin_layfontg.setText(str(color.green()))
                self.lin_layfontb.setText(str(color.blue()))
            elif target=='layout_paper':
                self.lin_laypaperr.setText(str(color.red()))
                self.lin_laypaperg.setText(str(color.green()))
                self.lin_laypaperb.setText(str(color.blue()))
            elif target=='layout_plot':
                self.lin_layplotr.setText(str(color.red()))
                self.lin_layplotg.setText(str(color.green()))
                self.lin_layplotb.setText(str(color.blue()))
            elif target=='xaxis':
                self.lin_xr.setText(str(color.red()))
                self.lin_xg.setText(str(color.green()))
                self.lin_xb.setText(str(color.blue()))
            elif target=='xaxis_title':
                self.lin_xtitler.setText(str(color.red()))
                self.lin_xtitleg.setText(str(color.green()))
                self.lin_xtitleb.setText(str(color.blue()))
            elif target=='xaxis_tick':
                self.lin_xtickr.setText(str(color.red()))
                self.lin_xtickg.setText(str(color.green()))
                self.lin_xtickb.setText(str(color.blue()))

    def layout_update(self):
        """Reads fields and updates parent's layout"""
        changes = AutoDictionary()

        # General
        if str(self.combo_layhover.currentText()) == 'False':
            changes['hovermode'] = False
        else:
            changes['hovermode'] = str(self.combo_layhover.currentText())
        changes['autosize'] = self.chk_layautosize.isChecked()
        changes['width'] = int(self.lin_laywidth.text())
        changes['height'] = int(self.lin_layheight.text())
        changes['font']['family'] = str(self.combo_layfont.currentText())
        changes['font']['size'] = int(self.lin_layfont.text())
        r = str(self.lin_layfontr.text())
        g = str(self.lin_layfontg.text())
        b = str(self.lin_layfontb.text())
        a = str(self.lin_layfonta.text())
        changes['font']['color'] = 'rgb('+r+','+g+','+b+','+a+')'
        r = str(self.lin_laypaperr.text())
        g = str(self.lin_laypaperg.text())
        b = str(self.lin_laypaperb.text())
        a = str(self.lin_laypapera.text())
        changes['paper_bgcolor'] = 'rgb('+r+','+g+','+b+','+a+')'
        r = str(self.lin_layplotr.text())
        g = str(self.lin_layplotg.text())
        b = str(self.lin_layplotb.text())
        a = str(self.lin_layplota.text())
        changes['plot_bgcolor'] = 'rgb('+r+','+g+','+b+','+a+')'
        changes['showlegend'] = self.chk_legend.isChecked()

        # Title
        changes['title']['text'] = str(self.lin_titletext.text())
        changes['title']['font']['family'] = str(self.combo_titlefont.currentText())
        changes['title']['font']['size'] = int(self.lin_titlefont.text())
        r = str(self.lin_titler.text())
        g = str(self.lin_titleg.text())
        b = str(self.lin_titleb.text())
        a = str(self.lin_titlea.text())
        changes['title']['font']['color'] = 'rgb('+r+','+g+','+b+','+a+')'

        # Run layout update
        self.parent.layout_update(changes=changes)

    def init_attributes(self):
        pass
